feat(doks-public) bump Kubernetes version from 1.26.to 1.27 digitalocean
jenkins-infra/digitalocean pull request #179
Opened 2024-02-15 09:39 UTC by smerle33

as per https://github.com/jenkins-infra/helpdesk/issues/3948 waiting for https://github.com/jenkins-infra/kubernetes-management/pull/4982

2024-02-15 09:48 UTC, dduportal requested changes
`No changes. Your infrastructure matches the configuration.` => it is unexpected. 

But there are warnings around 

```
Redundant ignore_changes element
  on doks-cluster.tf line 5 (and 3 more)
```


Which points to https://github.com/jenkins-infra/digitalocean/blob/c2e151a13b44397508319970d51bca44b335ed43/doks-cluster.tf#L17 (and the same on `doks-public`)

2024-02-15 09:49 UTC, smerle33 commented
> `No changes. Your infrastructure matches the configuration.` => it is unexpected.
> 
> But there are warnings around
> 
> ```
> Redundant ignore_changes element
>   on doks-cluster.tf line 5 (and 3 more)
> ```
> 
> Which points to
> 
> https://github.com/jenkins-infra/digitalocean/blob/c2e151a13b44397508319970d51bca44b335ed43/doks-cluster.tf#L17
> (and the same on `doks-public`)

match with https://github.com/jenkins-infra/digitalocean/pull/148

2024-02-15 09:50 UTC, dduportal commented
> `No changes. Your infrastructure matches the configuration.` => it is unexpected.
> 
> But there are warnings around
> 
> ```
> Redundant ignore_changes element
>   on doks-cluster.tf line 5 (and 3 more)
> ```
> 
> Which points to
> 
> https://github.com/jenkins-infra/digitalocean/blob/c2e151a13b44397508319970d51bca44b335ed43/doks-cluster.tf#L17
> (and the same on `doks-public`)

Looks like I did a manual upgrade last time: https://github.com/jenkins-infra/digitalocean/pull/167 and https://github.com/jenkins-infra/digitalocean/pull/168, which should not be. I remember the same kind of behavior leading me to "rush" the upgrade (hence the manually) but we might be able to fix this now that terraform 1.6+ is used (was 1.1 back then) as it relates to a terraform cycle here

2024-02-16 10:34 UTC, dduportal approved these changes
`Plan: 0 to add, 1 to change, 0 to destroy.`

LGTM

2024-02-16 10:34 UTC, merged